version: '3'

volumes:
    django_sample_db_dev: {}

services: 
    db:
        image: postgres
        volumes:
            - django_sample_db_dev:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=walkdb
            - POSTGRES_USER=sampleuser
            - POSTGRES_PASSWORD=samplesecret
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    
    django:
        build:
            context: .
            dockerfile: ./compose/django/dev.Dockerfile
        env_file:
            - django_src/credentials/dev.env
        environment:
            - DJANGO_DEBUG=True
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=5432
            - DJANGO_DB_NAME=walkdb
            - DJANGO_DB_USER=sampleuser
            - DJANGO_DB_PASSWORD=samplesecret
            - DJANGO_SECRET_KEY=dev_secret_key
        ports:
            - "8000:8000"
        volumes:
            - ./django_src:/app

    worker:
        build:
            context: .
            dockerfile: ./compose/worker/dev.Dockerfile
        environment:
            - DJANGO_DEBUG=True
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=5432
            - DJANGO_DB_NAME=walkdb
            - DJANGO_DB_USER=sampleuser
            - DJANGO_DB_PASSWORD=samplesecret
            - DJANGO_SECRET_KEY=dev_secret_key
        volumes:
            - ./django_src:/app
    
    rabbitmq:
        image: rabbitmq
        ports:
            - 5462:5462
        volumes:
            - ./django_src:/app