# Generated by Django 3.2.4 on 2021-06-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padded_Steps',
            fields=[
                ('rawsteps_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.rawsteps')),
            ],
            bases=('data.rawsteps',),
        ),
    ]
