# Generated by Django 3.2.4 on 2021-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_padded_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=255)),
                ('params', models.TextField(blank=True)),
                ('status', models.IntegerField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('depends', models.ManyToManyField(to='data.Task')),
            ],
        ),
    ]
