# Generated by Django 3.2.4 on 2021-06-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210623_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
