# Generated by Django 3.2.4 on 2021-06-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Padded_Steps',
        ),
    ]
