# Generated by Django 3.2.4 on 2021-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_binarywalked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageWalked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_datetime', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('mean_did_walked', models.FloatField()),
                ('local_date', models.DateField(blank=True, null=True)),
                ('local_time', models.TimeField(blank=True, null=True)),
                ('window_size', models.IntegerField()),
            ],
        ),
    ]
