# Generated by Django 3.2.4 on 2021-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210624_0746'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='binarywalked',
            name='data_binary_user_id_ac75a1_idx',
        ),
        migrations.AddIndex(
            model_name='binarywalked',
            index=models.Index(fields=['user_id', 'local_datetime'], name='data_binary_user_id_cee47f_idx'),
        ),
    ]
