# Generated by Django 3.2.4 on 2021-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210624_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryWalked2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_datetime', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('did_walked', models.IntegerField()),
                ('local_date', models.DateField(blank=True, null=True)),
                ('local_time', models.TimeField(blank=True, null=True)),
                ('window_size', models.IntegerField()),
                ('threshold1', models.FloatField()),
            ],
        ),
    ]
