# Generated by Django 3.2.4 on 2021-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_binarywalked2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('local_date', models.DateField()),
                ('step', models.IntegerField()),
                ('window_size', models.IntegerField()),
                ('threshold1', models.FloatField()),
                ('index_three_hour', models.IntegerField()),
                ('did_walked', models.IntegerField()),
            ],
        ),
    ]
