# Generated by Django 3.2.4 on 2021-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_threehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicted_Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('index_day', models.IntegerField()),
                ('step', models.IntegerField()),
                ('window_size', models.IntegerField()),
                ('threshold1', models.FloatField()),
                ('method', models.IntegerField()),
                ('n_days', models.IntegerField()),
                ('threshold2', models.FloatField()),
                ('TP', models.IntegerField()),
                ('TN', models.IntegerField()),
                ('FP', models.IntegerField()),
                ('FN', models.IntegerField()),
            ],
        ),
    ]
