# Generated by Django 3.2.4 on 2021-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_threehour_data_threeh_user_id_d87968_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_fetched', models.DateTimeField(blank=True, null=True)),
                ('when_finished', models.DateTimeField(blank=True, null=True)),
                ('sig_str', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
