# Generated by Django 3.2.4 on 2021-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregated1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_day', models.IntegerField()),
                ('index_method', models.IntegerField()),
                ('key_n_days', models.IntegerField()),
                ('key_window_size', models.IntegerField()),
                ('key_threshold1', models.FloatField()),
                ('key_threshold2', models.FloatField()),
                ('TP', models.IntegerField()),
                ('TN', models.IntegerField()),
                ('FP', models.IntegerField()),
                ('FN', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aggregated2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_method', models.IntegerField()),
                ('key_n_days', models.IntegerField()),
                ('key_window_size', models.IntegerField()),
                ('key_threshold1', models.FloatField()),
                ('key_threshold2', models.FloatField()),
                ('TP', models.IntegerField()),
                ('TN', models.IntegerField()),
                ('FP', models.IntegerField()),
                ('FN', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='aggregated2',
            index=models.Index(fields=['index_method', 'key_n_days', 'key_window_size', 'key_threshold1', 'key_threshold2'], name='analysis_ag_index_m_ccbaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregated1',
            index=models.Index(fields=['index_day', 'index_method', 'key_n_days', 'key_window_size', 'key_threshold1', 'key_threshold2'], name='analysis_ag_index_d_d4dba9_idx'),
        ),
    ]
