# Generated by Django 3.2.4 on 2021-06-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aggregated2',
        ),
    ]
