# Generated by Django 3.2.4 on 2021-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_depends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pkey',
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
