# Generated by Django 3.2.4 on 2021-06-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210623_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
